### ISSUE TITLE
Error after executing Digital Persona Fingerprint Bridge.exe

### ISSUE THREAD

**Issue by lbaclao** [tohenk/node-dpfb#5] opened 2021-01-28 01:14 UTC
Hello, I encountered this error after building the package. 

I tried also running `npm start` and it seems to work on the terminal but I'm not sure if it transmits the data to the browser client since I can't receive any output.

Did I miss something?

![Save](https://user-images.githubusercontent.com/65181260/106075491-ae9d0e00-6148-11eb-9ece-53c3152298b2.png)

**Comment by tohenk** [comment] 2021-01-28 01:36
To ensure the reader working properly try the following command using Command Prompt:
```
cd node_modules\@ntlab\dplib
node-gyp rebuild
npm run test
```
The output of `npm run test` should look like this:
```
D:\PROJ\Node\node-dpfb\node_modules\@ntlab\dplib>npm run test

> @ntlab/dplib@1.0.1 test D:\PROJ\Node\node-dpfb\node_modules\@ntlab\dplib
> node test/dplib.js

Readers: []
Please connect fingerprint reader...
Swipe your finger to enroll...
Finger acquired (1/4)
Finger acquired (2/4)
Finger acquired (3/4)
Finger acquired (4/4)
Enroll another finger...
Swipe your finger to enroll...
Finger acquired (1/4)
Finger acquired (2/4)
Finger acquired (3/4)
Finger acquired (4/4)
Enroll another finger...
Swipe your finger to enroll...
Finger acquired (1/4)
Finger acquired (2/4)
Finger acquired (3/4)
Finger acquired (4/4)
Enroll another finger...
Swipe your finger to enroll...
Finger acquired (1/4)
Finger acquired (2/4)
Finger acquired (3/4)
Finger acquired (4/4)
Swipe your finger to verify...
Finger matched at 2
It is done, exiting...
```

**Comment by lbaclao** [comment] 2021-01-28 02:05
The reader actually works and I managed to display the same output as you did but can't manage to get the samples to my client (browser) since I can't see any response from the events.

Any guide with that part?

**Comment by tohenk** [comment] 2021-01-28 02:50
It is a known limitation, make sure the DPFB app has focus not the browser app. Click the DPFP app icon one to make it focus.
![DPFBa](https://user-images.githubusercontent.com/350747/106082777-ea86a200-614d-11eb-85ca-5bd4f21e969f.png)
As seen on example, the focus is on Opera app, click the app icon (with arrow) to focus.
Then next try to swipe the finger on the reader.

**Comment by lbaclao** [comment] 2021-01-28 03:58
I see, but the problem is I can't seem to run the Digital Persona Fingerprint Bridge.exe due to that error I provided above.

**Comment by tohenk** [comment] 2021-01-28 04:16
It is caused by mixed up between electron being built is Win32, but the binding is Win64. It's should be fixed in 79bbc141107a4ec61e4cd96a9c1ac967a10d5865.

To build distribution package:
For Win32:
```
npm run build:win32
npm run package:win32
```
For Win64:
```
npm run build:win64
npm run package:win64
```

**Comment by lbaclao** [comment] 2021-01-28 04:48
I successfully built and run the app but the problem is there's no interface showing except it is only visible in my system tray. Is there suppose an interface popping after running the program?

![image](https://user-images.githubusercontent.com/65181260/106091266-00ed2780-6167-11eb-875e-02120842aa1b.png)

**Comment by tohenk** [comment] 2021-01-28 04:55
Only when it receives an event with `acquire` or `enroll`, it will show an app icon on taskbar along with Desktop Notification.

**Comment by tohenk** [comment] 2021-01-28 05:21
Here is a code snippet to test in browser.
```js
var fp = {
    url: 'http://localhost:7879',
    connected: null,
    sample: false,
    callback: null,
    enroll: function() {
        var self = this;
        if (self.connected) {
            self.socket.emit('enroll');
        }
    },
    acquire: function() {
        var self = this;
        if (self.connected) {
            self.socket.emit('acquire');
        }
    },
    init: function(callback) {
        var self = this;
        self.callback = callback;
        self.socket = io.connect(self.url, {reconnect: true});
        var notifyConnection = function() {
            $(document).trigger('fpconnect');
        }
        self.socket.on('connect', function() {
            self.socket.emit('self-test');
        });
        self.socket.on('disconnect', function() {
            self.connected = false;
            notifyConnection();
        });
        self.socket.on('self-test', function(response) {
            if (response) {
                var svrName = response.substr(0, response.indexOf('-'));
                var svrVer = response.substr(response.indexOf('-') + 1);
                if (svrName == 'DPFPBRIDGE') {
                    self.connected = true;
                    self.server = {name: svrName, protocol: svrVer};
                    console.log(self.server);
                    self.socket.emit('required-features');
                    self.socket.emit('set-options', {enrollWithSamples: self.sample});
                    notifyConnection();
                }
            }
        });
        self.socket.on('required-features', function(featuresLen) {
            self.featuresLen = featuresLen;
            console.log('Features length = %d', featuresLen);
        });
        self.socket.on('acquire-status', function(data) {
            console.log('Acquire status = %s', data.status);
            /*if (self.verifyDlg) {
                var msg;
                switch (data.status) {
                    case 'connected':
                        msg = 'Sentuhkan jari';
                        break;
                    case 'disconnected':
                        msg = 'Sambungkan pembaca sidik jari';
                        break;
                }
                if (msg) {
                    self.verifyDlg.find('.finger-op .msg').html(msg);
                }
            }*/
        });
        self.socket.on('acquire-complete', function(data) {
            console.log('Acquire complete = %s', data.data);
            /*if (self.verifyDlg) {
                if (typeof self.callback == 'function') {
                    self.callback('finger-acquired', data.data);
                }
            }*/
        });
        self.socket.on('enroll-status', function(data) {
            console.log('Enroll status = %s', data.status);
            /*if (self.enrollDlg) {
                var msg;
                switch (data.status) {
                    case 'connected':
                        msg = 'Sentuhkan jari %NR% kali'.replace(/%NR%/, self.featuresLen);
                        break;
                    case 'disconnected':
                        msg = 'Sambungkan pembaca sidik jari';
                        break;
                }
                if (msg) {
                    self.enrollDlg.find('.finger-op .msg').html(msg);
                }
            }*/
        });
        self.socket.on('enroll-complete', function(data) {
            console.log('Enroll complete = %s', data.data);
            /*if (self.enrollDlg) {
                self.enrollDlg.find('.finger-op .icon').addClass('text-success');
                setTimeout(function() {
                    self.enrollDlg.find('.finger-op .icon').removeClass('text-success');
                }, 500);
                if (self.enrollCount > 0) self.enrollCount--;
                if (self.enrollCount > 0) {
                    self.enrollDlg.find('.finger-op .msg').html('Sentuhkan jari %NR% kali'.replace(/%NR%/, self.enrollCount));
                } else {
                    self.enrollDlg.find('.finger-op .msg').html('Sentuhkan jari lagi');
                }
            }*/
        });
        self.socket.on('enroll-finished', function(data) {
            console.log('Enroll finished = %s', data.template);
            /*if (self.enrollDlg) {
                self.enrollDlg.find('.finger-op .msg').html('Pendaftaran sidik jari selesai');
                $.ntdlg.close(self.enrollDlg);
                if (typeof self.callback == 'function') {
                    self.callback('finger-enrolled', data.template);
                }
            }*/
        });
    }
}

// initialize fingerprint
fp.init(function(status, data) {
    switch (status) {
        case 'finger-acquired':
            /* do something */
            break;
    }
});

// when fingerprint connected do acquire fingerprint
$(document).on('fpconnect', function(e) {
    if (fp.connected) {
        fp.acquire();
    }
});

// stop operaiton when leaving page
$(window).on('beforeunload', function() {
    if (fp.connected) {
        fp.socket.emit('stop');
    }
});
```

**Comment by lbaclao** [comment] 2021-01-28 05:27
Awesome! I managed to get it working, still testing it though. Thanks for helping me out!

**Closed** 2021-01-28 07:38 UTC
